version: '3.9'
services:
  storage:
    image: 'redis:7.0.4-alpine'
    volumes: 
      - redis_data:/data
    restart: on-failure
    ports:
      - '6379:6379'
      - '8001:8001'
  counter-books:
    build: .
    ports:
      - '3002:3002'
    environment:
      - PORT=3002
      - REDIS_HOST=redis://storage
    depends_on:
      - storage

volumes:
  redis_data: {}
